# Generated by Django 5.2.1 on 2025-05-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_date_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=6),
        ),
    ]
