# Generated by Django 5.2.1 on 2025-05-13 21:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_therapist_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressjournal',
            old_name='entry',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='progressjournal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='progressjournal',
            name='session_feedback',
        ),
        migrations.AddField(
            model_name='progressjournal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='progressjournal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='progressjournal',
            name='mood',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
